kind: Service
apiVersion: v1
metadata:
  name: helloserver-service-zxh
spec:
  selector:
    app: helloserver-zxh
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-helloserver-zxh
  labels:
    app: helloserver-zxh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloserver-zxh
  template:
    metadata:
      labels:
        app: helloserver-zxh
    spec:
      imagePullSecrets:
      - name: harbor-registry
      containers:
      - name: helloserver-zxh
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
